### ISSUE TITLE
第三章校對

### ISSUE THREAD

**Issue by zerng07** [l10n-tw/designing-with-libreoffice#11]
就是這樣。

**Comment by fweng322** [comment]
初稿已完成，請校對。
裡面有些現在應該已經不存在的東西，有一兩小段沒有翻譯。圖片恐怕也都要重抓大改。
原稿應該是用 LibreOffice 4.4 為主，看翻譯本是否要以 5.x 系列為主，因為台灣政府單位現在使用的主要版本大多是 5.x。

另外，有些格式標籤我都索性通通拿掉。最後成品 odt 檔我們再用格式->字元之類的重新調整過一次。

**Comment by fweng322** [comment]
留意第三章裡有 reference pages number。最後需要重新 review 一次。

**Comment by zerng07** [comment]
我覺得可以用 5.4.4 的介面為主，是最後一個 5.x 版，這樣追上來的人都是同一個介面。

**Comment by zerng07** [comment]
等完成 5.x 線的版本後，接著再另外做個 6.0 版。

**Comment by zerng07** [comment]
校對完成。看有沒有其他人要再校閱的？

**Comment by zerng07** [comment]
已有一人校對，先關閉本議題。
有人要再校對時請再開 issue。或是之後全部章節完成後再來一次這樣。
