### ISSUE TITLE
第二章校對

### ISSUE THREAD

**Issue by zerng07** [l10n-tw/designing-with-libreoffice#13]
如題～

**Comment by fweng322** [comment]
第一次校對完成。
修改處有在譯者注記中註明。
有兩處譯者不明白的地方有做補充與修改，但最後一個（選取內容拖到視窗）試不出來。

請下一棒接力校對。

**Comment by zerng07** [comment]
已有一人校對，先關閉本議題。
有人要再校對時請再開 issue。或是之後全部章節完成後再來一次這樣。
