### ISSUE TITLE
關於明顯無意義的格式標籤的處置方式？

### ISSUE THREAD

**Issue by Vdragon** [l10n-tw/designing-with-libreoffice#18]
個人目前是直接無視這些標籤然後讓 OmegaT 警告

比較好的作法也許是回報上游把那些標籤移除掉？

**Comment by fweng322** [comment]
之前曾政嘉老大給的原則：

像這種明顯無意義的就直接刪掉：<f2> </f2>、<f0>B</f0>ut、bullet<f0>s</f0>

有意義的像是粗體、斜體那類會包住關鍵字或選單條目，就留下來。
像這個 <f0>modify them</f0> <f1>freely.</f1> 就是<f0>修改</f0>一組、<f1>隨意</1>一組。

兩者之間順序互夾也會出錯…是字元樣式。
