### ISSUE TITLE
自動建構當前修訂版的目標譯文文件

### ISSUE THREAD

**Issue by Vdragon** [l10n-tw/designing-with-libreoffice#19]
我想要用 Travis CI 直接建構目前版本的目標文件然後上傳到 GitHub Pages 讓大家可以存取最新版本翻好的內容

跟以下這個的作法差不多  
http://l10n.tw/l10n-tw-logo/

問題是 OmegaT 好像沒有在命令列界面下產生目標文件的能力？有辦法做到嗎？

**Comment by s8321414** [comment]
我是偏好一次譯完再生成啦......

**Comment by marklh9** [comment]
也可以用外部工具檢核每次上傳的xml……

2018年1月9日 17:07，"Ｖ字龍(Vdragon)" <notifications@github.com>寫道：

**Comment by Vdragon** [comment]
http://omegat.sourceforge.net/manual-standard/en/chapter.installing.and.running.html#omegat.command.arguments

晚點看看

**Comment by Vdragon** [comment]
自 0c91022 版本提交起初步搞定  
http://l10n.tw/designing-with-libreoffice/#%E7%95%B6%E5%89%8D%E8%AD%AF%E6%9C%AC%E4%B8%8B%E8%BC%89
