### ISSUE TITLE
第十二章校對

### ISSUE THREAD

**Issue by fweng322** [l10n-tw/designing-with-libreoffice#24]
第十二章已翻譯完成。但有不少地方是直接參考現有的修改而改寫。請校對。

**Comment by fweng322** [comment]
第十三章中 glue point 翻譯為「膠合點」，跟第十二章的翻法好像不太一樣，請校對第十二章時留意一下。

**Comment by s8321414** [comment]
你翻成什麼？

**Comment by zerng07** [comment]
第十二章沒有 glue point 耶。
一校完畢，看有沒有人要讀讀看順不順？

**Comment by zerng07** [comment]
既然兩次校對過，就關閉校對好了，等之後要再校再開～
