### ISSUE TITLE
第一章proofreading建議

### ISSUE THREAD

**Issue by Vdragon** [l10n-tw/designing-with-libreoffice#32]
參閱PDF註解，使用的版本是 c74963b
[chapter1-introduction.pdf](https://github.com/l10n-tw/designing-with-libreoffice/files/1711910/chapter1-introduction.pdf)

**Comment by zerng07** [comment]
部分我覺得合理或 OK 的建議有更新到翻譯中了。

剩下部分我覺得還好，就看有沒有其他意見可以討論討論～
