### ISSUE TITLE
將已完成初譯章節輸出為改作用的 odt 檔草稿

### ISSUE THREAD

**Issue by zerng07** [l10n-tw/designing-with-libreoffice#37]
查看 OmegaT 中的譯者注釋，把需要修改內文的地方以括號方式註記到翻譯字串中。

確認需要修改的字串位置都有附上提示後，輸出為改版草稿用的 odt 檔，並套用先前的草擬樣式後作為改作底稿。

再看看這些 odt 檔要放到哪裡好咧～
下一步就是展開改作認養、插圖重新擷圖認養。

**Comment by zerng07** [comment]
此步驟輸出的 odt 草稿和 pdf 檔也可以開始廣泛收集建議回饋，但不是所有回饋都要照單全收，而是根據寫作目標斟酌並適當修改即可。

**Comment by s8321414** [comment]
ODT 我覺得可以放到協會的 NextCloud 上。

**Comment by zerng07** [comment]
決議：放到協會的 NextCloud 上。各自用 client sync 在本機改，不要線上協作。

**Comment by zerng07** [comment]
待完成所有章節上傳至軟體自由協會 nextcloud 後時關閉本 issue。

**Comment by zerng07** [comment]
所有章節完成，近日會傳至 nextcloud 上。

**Comment by zerng07** [comment]
https://nextcloud.slat.org/index.php/s/pHmdyHDcKDpaxtZ 逐步上傳中。
