### ISSUE TITLE
第三章翻譯

### ISSUE THREAD

**Issue by fweng322** [l10n-tw/designing-with-libreoffice#4]
進行中，剛才的 Pull request 請不用理會，我改用 4.1.2 版試過後重提。

**Comment by zerng07** [comment]
可以參考這篇 https://libreo-zht.blogspot.tw/2017/12/omegat-4-github-designing-with.html

看看這篇哪裡有什麼內容還需要補進去的！XD
對了，還有 LibreOffice 會自動補中英之間的排版空間，所以翻譯 odt 檔時不必中英間補空格。

**Comment by fweng322** [comment]
感覺這一章的內容有點舊。例如 5.x 的版本應該已經沒有 TemplateMenu (翻譯字串中找不到)，還有現在用範本應該也不需要註冊 (Register)。只要把 .ott 檔放到指定路徑下就可以用了。到時候整體要再 Review 清楚。

**Comment by fweng322** [comment]
初稿已完成，請校對。
裡面有些現在應該已經不存在的東西，有一兩小段沒有翻譯。圖片恐怕也都要重抓大改。
原稿應該是用 LibreOffice 4.4 為主，看翻譯本是否要以 5.x 系列為主，因為台灣政府單位現在使用的主要版本大多是 5.x。

另外，有些格式標籤我都索性通通拿掉。最後成品 odt 檔我們再用格式->字元之類的重新調整過一次。
