### ISSUE TITLE
參照錯誤問題

### ISSUE THREAD

**Issue by Vdragon** [l10n-tw/designing-with-libreoffice#40]
我在第六章譯本注意到這個：

![screenshot_20180311_180122](https://user-images.githubusercontent.com/1192163/37252214-5115366a-2558-11e8-9f80-77996bc664a2.png)

**Comment by Vdragon** [comment]
看來必須要在 OmegaT 端實作翻譯參照名稱才行

**Comment by zerng07** [comment]
這是因為單獨開啟主控文件內子文件造成。但原作者公佈的封存檔中沒有這份主控文件。XD
