### ISSUE TITLE
擷圖並檢視與版本有關的內容正確性：第一章

### ISSUE THREAD

**Issue by fweng322** [l10n-tw/designing-with-libreoffice#50]
從 git 中的 target 開始每章檢視是否需要更新圖片與重新檢視描述的選單操作等是否符合 6.0.3 以上版本。

**Comment by fweng322** [comment]
第一章嘗試修改樣式並修正部份語句。
輸出至 target-edit 目錄。

**Comment by zerng07** [comment]
https://nextcloud.slat.org/index.php/s/pHmdyHDcKDpaxtZ
