### ISSUE TITLE
擷圖並檢視與版本有關的內容正確性：第二章

### ISSUE THREAD

**Issue by fweng322** [l10n-tw/designing-with-libreoffice#51]
需要修改圖片。

擷圖效果不好，待討論。

**Comment by fweng322** [comment]
已完成，圖片 2-6 視窗大小無法調整，擷圖以盡量讓它字看得清楚為原則。

**Comment by zerng07** [comment]
https://nextcloud.slat.org/index.php/s/pHmdyHDcKDpaxtZ
