### ISSUE TITLE
第十六章校對

### ISSUE THREAD

**Issue by s8321414** [l10n-tw/designing-with-libreoffice#8]
終於把第十六章翻完了，有空的人可以來協助校對 😄

**Comment by zerng07** [comment]
酷喔，我下週應該有時間看看～

**Comment by s8321414** [comment]
請小力鞭打（？）

**Comment by zerng07** [comment]
我完成了初校。
等看看有沒有其他輸入～

**Comment by fweng322** [comment]
選單的表示法要統一。
我（第三章）的用法是「檔案」>「另存新檔」，這一章的用法是「檔案 → 另存新檔」。

分節 3021, 3037, 3056, 3073, 3099, 3102, 

@zerng07

**Comment by zerng07** [comment]
經由 @zerng07 和 @fweng322 校閱過，關閉本伊羞。
